plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.140'
}

abstract class TeaConDumpPathToGitHub extends DefaultTask {
    @Input
    abstract Property<String> getPublishName()

    @InputFile
    abstract RegularFileProperty getTargetFile()

    @TaskAction
    void dump() {
        if (System.env.GITHUB_ACTIONS) {
            File theFile = targetFile.getAsFile().get()

            def outputFile = new File(System.env.GITHUB_OUTPUT)
            // Use the env-specific line separator for maximally possible compatibility
            def newLine = System.getProperty('line.separator')

            // Write out new env variable for later usage
            outputFile << newLine << "artifact_name=${theFile.getName()}"
            outputFile << newLine << "artifact_publish_name=${publishName.get()}"
            outputFile << newLine << "artifact_path=${theFile.absolutePath}"
        }
    }
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

repositories {
    mavenLocal()
}

base {
    archivesName = mod_id
}
// Source - https://stackoverflow.com/a/35707023
// Posted by DallinDyer, modified by community. See post 'Timeline' for change history
// Retrieved 2026-03-25, License - CC BY-SA 3.0

allprojects {
    gradle.projectsEvaluated {
        tasks.withType(JavaCompile) {
            options.compilerArgs << "-Xmaxerrs" << "10000"
        }
    }
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

neoForge {
    // Specify the version of NeoForge to use.
    version = project.neo_version

    accessTransformers {
        file('src/main/resources/META-INF/accesstransformer.cfg')
    }
    runs {
        client {
            client()

            // Comma-separated list of namespaces to load gametests from. Empty = all namespaces.
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
            systemProperty 'neoforge.disableGlValidation', 'true'
        }

        clientRenderDoc {
            client()

            // Comma-separated list of namespaces to load gametests from. Empty = all namespaces.
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
            systemProperty 'neoforge.disableGlValidation', 'true'
            systemProperty('neoforge.rendernurse.renderdoc.library', file("libs/renderdoc.dll").absolutePath)
            systemProperty('mixin.debug.export', 'true')
            jvmArgument("-javaagent:" + file("libs/renderdoc-loader.jar").absolutePath)

            programArgument("--renderDebugLabels")
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            clientData()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        // applies to all the run configs above
        configureEach {
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

// Include resources generated by data generators.
sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

repositories {
    maven {
        name = "Curse maven"
        url = "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        name = "caffeinemcRepositoryReleases"
        url = uri("https://maven.caffeinemc.net/releases")
    }
    maven {
        name = "IrisShaders maven"
        url = "https://maven.irisshaders.dev/releases"
    }
    maven {
        // location of the maven that hosts JEI files since January 2023
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        // location of a maven mirror for JEI files, as a fallback
        name = "ModMaven"
        url = "https://modmaven.dev"
    }
    maven { // Embeddium, Sodium, Iris
        name = "Modrinth Maven"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
    maven {
        url "https://maven.su5ed.dev/releases"
    }
    maven {
        // Placeholder API NeoForge
        name = "OffsetMonkey538"
        url = "https://maven.offsetmonkey538.top/releases"
    }
}

dependencies {

    compileOnly "maven.modrinth:jade:${jade_version}"
    localRuntime "maven.modrinth:jade:${jade_version}"

    compileOnly "mezz.jei:jei-${minecraft_version}-common-api:${jei_version}"
    compileOnly "mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}"
    implementation "mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}"

    compileOnly("net.caffeinemc:sodium-neoforge-mod:0.8.12+mc26.1.2") // sodium mc26.1.2-0.8.12-neoforge
    compileOnly("maven.modrinth:YL57xq9U:YEGDGnJM") // iris 1.10.9+26.1-neoforge

    jarJar(implementation "eu.pb4:placeholder-api-neoforge:3.0.0+26.1+neoforge") {
        version {
            prefer "3.0.0"
        }
    }

    jarJar(implementation "com.xkball:xklib-3d:$xklib_version") {
        version {
            strictly "[$xklib_version, 1.0.0)"
            prefer xklib_version
        }
    }
    jarJar(implementation "com.xkball:xklib-ap:$xklib_version") {
        version {
            strictly "[$xklib_version, 1.0.0)"
            prefer xklib_version
        }
    }
    jarJar(implementation "com.xkball:xklib-ui:$xklib_version") {
        version {
            strictly "[$xklib_version, 1.0.0)"
            prefer xklib_version
        }
    }
    jarJar(implementation "com.xkball:xklib-mc:$xklib_version") {
        version {
            strictly "[$xklib_version, 1.0.0)"
            prefer xklib_version
        }
    }
    jarJar(implementation "dev.vfyjxf:taffy:1.1.4") {
        version {
            strictly '[1.1.4, 2.0.0)'
            prefer '1.1.4'
        }
    }
    jarJar(implementation "org.antlr:antlr4-runtime:4.13.2") {
        version {
            strictly '[4.13.2, 5.0.0)'
            prefer '4.13.2'
        }
    }
    jarJar(implementation "net.lenni0451:LambdaEvents:2.4.2") {
        version {
            strictly '[2.4.2, 3.0.0)'
            prefer '2.4.2'
        }
    }
}

// This block of code expands all declared replace properties in the specified resource targets.
// A missing property will result in an error. Properties are expanded using ${} Groovy notation.
// When "copyIdeResources" is enabled, this will also run before the game launches in IDE environments.
// See https://docs.gradle.org/current/dsl/org.gradle.language.jvm.tasks.ProcessResources.html
tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

publishing { PublishingExtension it ->
    publications {
        // noinspection GroovyAssignabilityCheck
        release(MavenPublication) {
            // noinspection GroovyAssignabilityCheck
            from components.java
            // noinspection GroovyAssignabilityCheck
            groupId = "org.teacon"
            // noinspection GroovyAssignabilityCheck
            artifactId = 'PowerTool-NeoForge-26.1'
            // noinspection GroovyAssignabilityCheck
            version = mod_version
            pom {
                // noinspection GroovyAssignabilityCheck
                name = 'PowerTool'
                // noinspection GroovyAssignabilityCheck
                url = "https://github.com/teaconmc/PowerTool"
                licenses {
                    license {
                        // noinspection GroovyAssignabilityCheck
                        name = 'GPLv3'
                        // noinspection GroovyAssignabilityCheck
                        url = "https://github.com/teaconmc/PowerTool/blob/26.1-neoforge/LICENSE"
                    }
                }
                organization {
                    // noinspection GroovyAssignabilityCheck
                    name = 'TeaConMC'
                    // noinspection GroovyAssignabilityCheck
                    url = 'https://github.com/teaconmc'
                }
                developers {
                    developer {
                        id = '3TUSK'
                        name = '3TUSK'
                    }
                    developer {
                        id = 'xkball'
                        name = 'xkball'
                    }
                }
                issueManagement {
                    // noinspection GroovyAssignabilityCheck
                    system = 'GitHub Issues'
                    // noinspection GroovyAssignabilityCheck
                    url = "https://github.com/teaconmc/PowerTool/issues"
                }
                scm {
                    // noinspection GroovyAssignabilityCheck
                    url = "https://github.com/teaconmc/PowerTool"
                    // noinspection GroovyAssignabilityCheck
                    connection = "scm:git:git://github.com/teaconmc/PowerTool.git"
                    // noinspection GroovyAssignabilityCheck
                    developerConnection = "scm:git:git@github.com:teaconmc/PowerTool.git"
                }
            }
        }
    }
    repositories {
        maven {
            name = "teacon"
            url = "s3://maven/"
            credentials(AwsCredentials) {
                accessKey = System.env.ARCHIVE_ACCESS_KEY
                secretKey = System.env.ARCHIVE_SECRET_KEY
            }
        }
    }
}

tasks.withType(PublishToMavenRepository).configureEach {
    if (repository && repository.name == "teacon") {
        it.onlyIf {
            System.env.ARCHIVE_ACCESS_KEY && System.env.ARCHIVE_SECRET_KEY
        }
    }
}

tasks.register("githubActionOutput", TeaConDumpPathToGitHub) { task ->
    task.onlyIf {
        System.env.GITHUB_ACTIONS
    }
    task.getPublishName().set("${jar.archiveBaseName.get()}-${version}.jar")
    task.getTargetFile().set(jar.archiveFile)
}
